name: Go

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./downloader # There is only a test in this folder

    - name: Build
      if: success()
      run: |
        GOOS=windows go build -ldflags "-s -w"
        GOOS=darwin go build -o gitmoo-goog-osx -ldflags "-s -w"
        go build -ldflags "-s -w" -o gitmoo-goog
        cd installer
        go build
        ./installer
        cd ..
        zip gitmoo-goog.zip installer/*.deb gitmoo-goog gitmoo-goog-osx gitmoo-goog.exe

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: "gitmoo-goog.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
